version: '3'

x-besu:
  &besu
  image: "hyperledger/besu:develop"
  mem_limit: 500M

services:
  besu1:
    << : *besu
    volumes:
      - ./docker-config:/config
      - ./docker-data/node1:/data
    ports:
      - "8545:8545"
    entrypoint:
      - /opt/besu/bin/besu
      - --data-path=/data
      - --genesis-file=/config/genesis.json
      - --node-private-key-file=/config/besu-keystore/besu1-key
      - --permissions-accounts-contract-enabled
      - --permissions-accounts-contract-address=0x0000000000000000000000000000000000008888
      - --revert-reason-enabled
      - --host-whitelist=*
      - --graphql-http-enabled
      - --rpc-http-enabled
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ADMIN,ETH,NET,PERM,CLIQUE
      - --discovery-enabled=true

  besu2:
    << : *besu
    volumes:
      - ./docker-config:/config:ro
      - ./docker-data/node2:/data
    entrypoint:
      - /opt/besu/bin/besu
      - --data-path=/data
      - --genesis-file=/config/genesis.json
      - --node-private-key-file=/config/besu-keystore/besu2-key
      - --revert-reason-enabled
      - --host-whitelist=*
      - --graphql-http-enabled
      - --permissions-accounts-contract-enabled
      - --permissions-accounts-contract-address=0x0000000000000000000000000000000000008888
      - --rpc-http-enabled
      - --rpc-http-cors-origins=*
      - --discovery-enabled=true
      - --bootnodes=enode://823e8c26c73e20391a21ed9a8812e1a10d479c9a12d2beb48adf3a0b4e1edcddbcc5aa590ccec56fe493ba53f9f7bee497eb39fa82aba9b688ade729b142c960@besu1:30303
      - --Xdns-enabled=true

  besu3:
    << : *besu
    volumes:
      - ./docker-config:/config:ro
      - ./docker-data/node3:/data
    entrypoint:
      - /opt/besu/bin/besu
      - --data-path=/data
      - --genesis-file=/config/genesis.json
      - --node-private-key-file=/config/besu-keystore/besu3-key
      - --revert-reason-enabled
      - --host-whitelist=*
      - --graphql-http-enabled
      - --permissions-accounts-contract-enabled
      - --permissions-accounts-contract-address=0x0000000000000000000000000000000000008888
      - --rpc-http-enabled
      - --rpc-http-cors-origins=*
      - --discovery-enabled=true
      - --bootnodes=enode://823e8c26c73e20391a21ed9a8812e1a10d479c9a12d2beb48adf3a0b4e1edcddbcc5aa590ccec56fe493ba53f9f7bee497eb39fa82aba9b688ade729b142c960@besu1:30303
      - --Xdns-enabled=true
